version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: vss77/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media

  frontend:
    env_file: .env
    image: vss77/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
    depends_on:
      - backend
    
  gateway:
    image: vss77/kittygram_gateway
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    ports:
      - 9000:80
    depends_on:
      - frontend